### ISSUE TITLE
Drop Elixir in favour of Erlang/Gleam

### ISSUE THREAD

**Issue by darky** [patrik-kuehl/gleamyshell#26]
### Proposal

Seems all Elixir code can be rewritten to Gleam with Erlang bindings
It's will reduce requirement to install Elixir for **gleamyshell**

**Comment by patrik-kuehl** [comment]
I didn't consider Elixir to be a burden for people, and I'm more comfortable with Elixir, but getting rid of an avoidable dependency never sounds bad.

Although I don't consider this a high priority as of now, I'm writing some issues on the weekend. Each issue shall replace one Elixir function with an Erlang equivalent. Getting rid of Elixir incrementally.

I keep this issue open, acting as a parent work item.

**Comment by patrik-kuehl** [comment]
Note: This issue has been closed because the entire Elixir-based FFI implementation is now Erlang-based.

**Comment by darky** [comment]
Awesome, thanks! Bump new version please, I will use **gleamyshell** in my projects.

**Comment by patrik-kuehl** [comment]
Haha! Didn't expect such a quick response. Sure, will do it in around an hour (gotta buy groceries).
